build:
  test:
    image: golang:1.5
    environment:
      - CGO_ENABLED=0
      - GO15VENDOREXPERIMENT=1
    commands:
      - go vet
      - go test
      - go build -ldflags "-s -w -X main.version=$DRONE_BUILD_NUMBER"
    when:
      event: push

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: zywillc/drone-chef-client
    tag: latest

plugin:
  name: drone-chef-client
  desc: drone chef client plugin
  type: publish|deploy|notify|clone|cache
  image: zywillc/drone-chef-client
  labels:
    - 0.1
